version: 2.1

jobs:
  build:
    docker:
      - image: node:20.4.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install --force
      - run:
          name: Build Prisma db
          command: npx prisma generate
      - run:
          name: Add Prisma db
          command: npx prisma db push
      - run:
          name: Build TypeScripta
          command: npm run build 
